spring:
  application:
    name: spring-boot-starter-custom
  profiles:
    include: mail,wenky #,redis
  # true: 默认cglib
  # false: 指定jdk代理
  aop:
    proxy-target-class: true
# post => 请求参数和响应结果 @RequestBody
# get => 响应结果
#  jackson:
#    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

# 项目引用该jar时配置文件后缀应为yml,否则该默认配置不会生效
wenky:
  auto:
    string: ONE
    auto-enum: first
    a-boolean: false
    a-long: 1
    integer: 1
  aspect:
    controller: enable

#server:
#  tomcat:
#    max-threads: 1